.TH MACRANDRD 8
.SH NAME
macrandrd \- OpenBSD MAC address randomization daemon
.SH SYNOPSIS
.B macrandrd
[\fB\-v\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B macrandrd id a tiny OpenBSD MAC address randomization daemon
modifies MAC address every 30 seconds of every active network interface except
for the following interfaces lo0 enc0 pflog0.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.
